version: '3'

services:
  ci:
    image: tradingai/bazel:latest
    command:
      /bin/bash /go/src/github.com/tradingAI/proto/docker-compose.sh
    volumes:
      - .:/go/src/github.com/tradingAI/proto/
